version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3006:80'
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
    volumes:
      - /app/node_modules
      - ./api:/app
  ui:
    build:
      dockerfile: Dockerfile
      context: ./ui
    volumes:
      - /app/node_modules
      - ./ui:/app
    ports:
      - '8080:8080'